import datetime
from database import Genre, Book

genres_data = [
    Genre(name="Фантастика",),
    Genre(name="Детектив",),
    Genre(name="Роман",),
    Genre(name="Фэнтези",),
    Genre(name="Научная литература",),
]

books_data = [
    Book(title="Дюна", genre=genres_data[0], added=datetime.datetime.strptime('2020-01-15', "%Y-%m-%d"), author="Фрэнк Герберт"),
    Book(title="1984", genre=genres_data[0], added=datetime.datetime.strptime('2020-02-20', "%Y-%m-%d"), author="Джордж Оруэлл"),
    Book(title="Война миров", genre=genres_data[0], added=datetime.datetime.strptime('2020-03-10', "%Y-%m-%d"), author="Герберт Уэллс"),
    Book(title="Марсианин", genre=genres_data[0], added=datetime.datetime.strptime('2020-04-05', "%Y-%m-%d"), author="Энди Уир"),
    Book(title="Мечтают ли андроиды об электроовцах?", genre=genres_data[0], added=datetime.datetime.strptime('2020-05-12', "%Y-%m-%d"), author="Филип К. Дик"),
    Book(title="Град обреченный", genre=genres_data[0], added=datetime.datetime.strptime('2020-06-18', "%Y-%m-%d"), author="Борис Стругацкий, Аркадий Стругацкий"),
    Book(title="Солярис", genre=genres_data[0], added=datetime.datetime.strptime('2020-07-25', "%Y-%m-%d"), author="Станислав Лем"),
    Book(title="Атлант расправил плечи", genre=genres_data[0], added=datetime.datetime.strptime('2020-08-30', "%Y-%m-%d"), author="Айн Рэнд"),
    Book(title="Эдем", genre=genres_data[0], added=datetime.datetime.strptime('2020-09-07', "%Y-%m-%d"), author="Станислав Лем"),
    Book(title="Звездные войны: Империя наносит ответный удар", genre=genres_data[0], added=datetime.datetime.strptime('2020-10-14', "%Y-%m-%d"), author="Дэймон Линделоф"),
    Book(title="Убийство в Восточном экспрессе", genre=genres_data[1], added=datetime.datetime.strptime('2020-11-21', "%Y-%m-%d"), author="Агата Кристи"),
    Book(title="Шерлок Холмс: Собака Баскервилей", genre=genres_data[1], added=datetime.datetime.strptime('2020-12-28', "%Y-%m-%d"), author="Артур Конан Дойл"),
    Book(title="Тайна Ричарда III", genre=genres_data[1], added=datetime.datetime.strptime('2021-01-04', "%Y-%m-%d"), author="Филиппа Грегори"),
    Book(title="Мальтийский сокол", genre=genres_data[1], added=datetime.datetime.strptime('2021-02-11', "%Y-%m-%d"), author="Дэшил Хэммет"),
    Book(title="Смерть на Ниле", genre=genres_data[1], added=datetime.datetime.strptime('2021-03-18', "%Y-%m-%d"), author="Агата Кристи"),
    Book(title="Убийство в Восточном экспрессе", genre=genres_data[1], added=datetime.datetime.strptime('2021-04-25', "%Y-%m-%d"), author="Агата Кристи"),
    Book(title="Шерлок Холмс: Знак четырех", genre=genres_data[1], added=datetime.datetime.strptime('2021-05-02', "%Y-%m-%d"), author="Артур Конан Дойл"),
    Book(title="Тайна Ричарда III", genre=genres_data[1], added=datetime.datetime.strptime('2021-06-09', "%Y-%m-%d"), author="Филиппа Грегори"),
    Book(title="Мальтийский сокол", genre=genres_data[1], added=datetime.datetime.strptime('2021-07-16', "%Y-%m-%d"), author="Дэшил Хэммет"),
    Book(title="Смерть на Ниле", genre=genres_data[1], added=datetime.datetime.strptime('2021-08-23', "%Y-%m-%d"), author="Агата Кристи"),
    Book(title="Гордость и предубеждение", genre=genres_data[2], added=datetime.datetime.strptime('2021-09-30', "%Y-%m-%d"), author="Джейн Остин"),
    Book(title="Великий Гэтсби", genre=genres_data[2], added=datetime.datetime.strptime('2021-10-07', "%Y-%m-%d"), author="Ф. Скотт Фицджеральд"),
    Book(title="Убить пересмешника", genre=genres_data[2], added=datetime.datetime.strptime('2021-11-14', "%Y-%m-%d"), author="Харпер Ли"),
    Book(title="Сто лет одиночества", genre=genres_data[2], added=datetime.datetime.strptime('2021-12-21', "%Y-%m-%d"), author="Габриэль Гарсиа Маркес"),
    Book(title="Три товарища", genre=genres_data[2], added=datetime.datetime.strptime('2022-01-28', "%Y-%m-%d"), author="Эрих Мария Ремарк"),
    Book(title="Тихий дон", genre=genres_data[2], added=datetime.datetime.strptime('2022-02-04', "%Y-%m-%d"), author="Михаил Шолохов"),
    Book(title="Анна Каренина", genre=genres_data[2], added=datetime.datetime.strptime('2022-03-11', "%Y-%m-%d"), author="Лев Толстой"),
    Book(title="Над пропастью во ржи", genre=genres_data[2], added=datetime.datetime.strptime('2022-04-18', "%Y-%m-%d"), author="Джером Д. Сэлинджер"),
    Book(title="Дом, где разбиваются сердца", genre=genres_data[2], added=datetime.datetime.strptime('2022-05-25', "%Y-%m-%d"), author="Эрнест Хемингуэй"),
    Book(title="Унесенные ветром", genre=genres_data[2], added=datetime.datetime.strptime('2022-06-01', "%Y-%m-%d"), author="Маргарет Митчелл"),
    Book(title="Властелин колец", genre=genres_data[3], added=datetime.datetime.strptime('2022-07-08', "%Y-%m-%d"), author="Дж. Р. Р. Толкин"),
    Book(title="Гарри Поттер и философский камень", genre=genres_data[3], added=datetime.datetime.strptime('2022-08-15', "%Y-%m-%d"), author="Джоан Роулинг"),
    Book(title="Песнь льда и огня: Игра престолов", genre=genres_data[3], added=datetime.datetime.strptime('2022-09-22', "%Y-%m-%d"), author="Джордж Мартин"),
    Book(title="Хроники Нарнии: Лев, колдунья и волшебный шкаф", genre=genres_data[3], added=datetime.datetime.strptime('2022-10-29', "%Y-%m-%d"), author="Клайв С. Льюис"),
    Book(title="Американские боги", genre=genres_data[3], added=datetime.datetime.strptime('2022-11-05', "%Y-%m-%d"), author="Нил Гейман"),
    Book(title="Темная башня", genre=genres_data[3], added=datetime.datetime.strptime('2022-12-12', "%Y-%m-%d"), author="Стивен Кинг"),
    Book(title="Ведьмак: Последнее желание", genre=genres_data[3], added=datetime.datetime.strptime('2023-01-19', "%Y-%m-%d"), author="Анджей Сапковский"),
    Book(title="Хроники Амбера", genre=genres_data[3], added=datetime.datetime.strptime('2023-02-26', "%Y-%m-%d"), author="Роджер Желязны"),
    Book(title="Мерцание", genre=genres_data[3], added=datetime.datetime.strptime('2023-03-05', "%Y-%m-%d"), author="Стивен Кинг"),
    Book(title="Хроники Заводной птицы", genre=genres_data[3], added=datetime.datetime.strptime('2023-04-12', "%Y-%m-%d"), author="Харуки Мураками"),
    Book(title="Бог как иллюзия", genre=genres_data[4], added=datetime.datetime.strptime('2023-05-19', "%Y-%m-%d"), author="Ричард Докинз"),
    Book(title="Структура научных революций", genre=genres_data[4], added=datetime.datetime.strptime('2023-06-26', "%Y-%m-%d"), author="Томас Кун"),
    Book(title="Эгоистичный ген", genre=genres_data[4], added=datetime.datetime.strptime('2023-07-03', "%Y-%m-%d"), author="Ричард Докинз"),
    Book(title="Конец веры", genre=genres_data[4], added=datetime.datetime.strptime('2023-08-10', "%Y-%m-%d"), author="Сэм Харрис"),
    Book(title="Слепой часовщик", genre=genres_data[4], added=datetime.datetime.strptime('2023-09-17', "%Y-%m-%d"), author="Ричард Докинз"),
    Book(title="Структура научных революций", genre=genres_data[4], added=datetime.datetime.strptime('2023-10-24', "%Y-%m-%d"), author="Томас Кун"),
    Book(title="Эгоистичный ген", genre=genres_data[4], added=datetime.datetime.strptime('2023-11-30', "%Y-%m-%d"), author="Ричард Докинз"),
    Book(title="Конец веры", genre=genres_data[4], added=datetime.datetime.strptime('2023-12-07', "%Y-%m-%d"), author="Сэм Харрис"),
    Book(title="Слепой часовщик", genre=genres_data[4], added=datetime.datetime.strptime('2024-01-14', "%Y-%m-%d"), author="Ричард Докинз"),
    Book(title="Структура научных революций", genre=genres_data[4], added=datetime.datetime.strptime('2024-02-21', "%Y-%m-%d"), author="Томас Кун")
]